# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files to the extra_config_files directory to override
# the settings in this file

# Directory in which to place config overrides
extra_config_files: /etc/wazo-load-pilot/conf.d/

update_policy_on_startup: True

log_filename: /var/log/wazo-load-pilot.log
debug: False

# REST API server
rest_api:
  listen: 0.0.0.0
  port: 9990

resolvconf:
  hostname_file: /etc/hostname
  hosts_file: /etc/hosts
  resolvconf_file: /etc/resolv.conf
